SSAFY/dbdb/20231017/강사님 실습/03-01-many-to-many-relationships/accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('profile/<username>/', views.profile, name="profile"),
    path('<int:user_pk>/follow/', views.follow, name="follow"),
]

SSAFY/dbdb/20231017/강사님 실습/03-01-many-to-many-relationships/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from articles.models import Article

# Create your models here.
class User(AbstractUser):
    followings = models.ManyToManyField('self', symmetrical=False, related_name='followers')
    pass

SSAFY/dbdb/20231017/강사님 실습/03-01-many-to-many-relationships/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.contrib.auth import get_user_model
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
from .forms import CustomUserCreationForm, CustomUserChangeForm

# Create your views here.
def login(request):
    if request.user.is_authenticated:
        return redirect('articles:index')

    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect('articles:index')
    else:
        form = AuthenticationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/login.html', context)


@login_required
def logout(request):
    auth_logout(request)
    return redirect('articles:index')


def signup(request):
    if request.user.is_authenticated:
        return redirect('articles:index')

    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('articles:index')
    else:
        form = CustomUserCreationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/signup.html', context)


@login_required
def delete(request):
    request.user.delete()
    return redirect('articles:index')


@login_required
def update(request):
    if request.method == 'POST':
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('articles:index')
    else:
        form = CustomUserChangeForm(instance=request.user)
    context = {
        'form': form,
    }
    return render(request, 'accounts/update.html', context)


@login_required
def change_password(request, user_pk):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            return redirect('articles:index')
    else:
        form = PasswordChangeForm(request.user)
    context = {
        'form': form,
    }
    return render(request, 'accounts/change_password.html', context)


def profile(request, username):
    person = get_user_model().objects.get(username=username)
    context = {
        'person':person
    }
    return render(request, 'accounts/profile.html',context)


def follow(request, user_pk):
    person = get_user_model().objects.get(pk=user_pk)
    if person.followers.filter(pk=request.user.pk).exists():
        person.followers.remove(request.user)
    else:
        person.followers.add(request.user)
    return redirect('accounts:profile', person.username)

SSAFY/dbdb/20231017/강사님 실습/03-01-many-to-many-relationships/accounts/templates/accounts/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>프로필</h1>
    사용자 이름 : {{ person.username }}
    <hr>
    {{ person.username }}가 팔로우하는 사용자들 :
    <p>{{ person.followings.all|length }}명</p>
    {% for following in person.followings.all %}
        <p>{{ following.username }}</p>
    {% endfor %}
    <hr>
    {{ person.username }}를 팔로우하는 사용자들 :
    <p>{{ person.followers.all|length }}명</p>
    {% for follower in person.followers.all %}
        <p>{{ follower.username }}</p>
    {% endfor %}
    <form action="{% url "accounts:follow" person.pk %}" method="post">
        {% csrf_token %}
        {% if request.user in person.followers.all %}
            <input type="submit" value="팔로우 취소">
        {% else %}
            <input type="submit" value="팔로우">
        {% endif %}
    </form>
    <hr>
    {{ person.username }}가 작성한 게시글들 :
    {% for article in person.article_set.all %}
        <p><a href="{% url "articles:detail" article.pk %}" >{{ article.title }}</a></p>
    {% endfor %}
    <hr>
    {{ person.username }}가 작성한 댓글들 :
    {% for comment in person.comment_set.all %}
        <p>{{ comment.content }}</p>
    {% endfor %}
    <hr>
</body>
</html>