SSAFY/django/20230926/my_pjt/articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'
urlpatterns = [
    path('index/', views.index, name='index'),
    path('new/', views.new, name='new'),
    path('create/', views.create, name='create'),
    path('delete/<int:pk>/', views.delete, name='delete'),
    path('detail/<int:pk>/', views.detail, name='detail'),
]

SSAFY/django/20230926/my_pjt/my_pjt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls'))
]

SSAFY/django/20230926/my_pjt/articles/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=20)
    content = models.TextField()
    

SSAFY/django/20230926/my_pjt/articles/views.py
from django.shortcuts import render, redirect
from .models import Article


# Create your views here.
def index(request):
    articles = Article.objects.all()
    context = {
        'articles' : articles
    }
    return render(request, 'articles/index.html', context)

def new(request):
    return render(request, 'articles/new.html')

def create(request):
    title = request.POST.get('title')
    content = request.POST.get('content')
    article = Article(title=title, content=content)
    article.save()
    return redirect('articles:index')

def delete(request,pk):
    article = Article.objects.get(pk=pk)
    article.delete()
    return redirect('articles:index')

def detail(request, pk):
    article = Article.objects.get(pk=pk)
    context = {
        'article' : article
    }
    return render(request, 'articles/detail.html', context)

SSAFY/django/20230926/my_pjt/articles/templates/articles/detail.html
{% extends "base.html" %}

{% block content %}
<h1>여기는 DETAIL입니다.</h1>
<hr>
<h1>제목 : {{ article.title }}</h1>
<p>내용 : <br>{{ article.content }}</p>
<hr>
<form action="{% url "articles:delete" article.pk%}">
  <input type="submit" value="삭제">
</form>


{% endblock content %}

SSAFY/django/20230926/my_pjt/articles/templates/articles/index.html
{% extends "base.html" %}

{% block content %}
<h1>여기는 INDEX입니다.</h1>
<a href="{% url "articles:new" %}"><button>글작성</button></a>
<hr>
{% for article in articles %}
<p>제목 : <a href="{% url "articles:detail" article.pk%}">{{ article.title }}</a></p>
<p>내용 : <br>{{ article.content }}</p>
<form action="{% url "articles:delete" article.pk%}">
  <input type="submit" value="삭제">
</form>
<hr>
{% endfor %}

{% endblock content %}

SSAFY/django/20230926/my_pjt/articles/templates/articles/new.html
{% extends "base.html" %}

{% block content %}
<h1>여기는 NEW입니다.</h1>
<hr>
<form action="{% url "articles:create" %}" method='POST'>
  {% csrf_token %}
  <div>
  <label for="title">제목 : </label>
  <input type="text" name="title" id="title">
  </div>
  <div>
  <label for="content">내용 : </label>
  <textarea name="content" id="" cols="30" rows="10"></textarea>
  </div>
  <input type="submit" value="작성">
</form>


<a href="{% url "articles:index" %}"><button>뒤로가기</button></a>

{% endblock content %}