SSAFY/django/20230913/실습/pratice/articles/urls.py
from django.urls import path
from . import views
app_name = "articles"

urlpatterns = [
    path('index/', views.index, name="index"),
    path('throw/', views.throw, name="throw"),
    path('catch/', views.catch, name="catch"),
    path('catchh/<name>', views.catchh, name="catchh"),
]

SSAFY/django/20230913/실습/pratice/pratice/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls'))
]

SSAFY/django/20230913/실습/pratice/articles/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, "articles/index.html")

def throw(request):
    return render(request, "articles/throw.html")

def catch(request):
    message = request.GET.get('message')
    context = {
        'message' : message,
        'a' : [1,2,3,4,5],
    }
    return render(request, "articles/catch.html", context)

def catchh(request,name):
    context = {
        'name' : name
    }
    return render(request, "articles/catchh.html",context)

SSAFY/django/20230913/실습/pratice/articles/templates/articles/catch.html
{% extends "base.html" %}

{% block content %}
<div class="container">
  <h1>Catch</h1>
  {% for i in a %}
    <h1>
      {{ message }} {{i}}
    </h1>
    <br>
  {% endfor %}
  <a href="{% url "articles:index" %}">index로 이동</a><br>
  <a href="{% url "articles:throw" %}">Throw로 이동</a>
 
</div>

{% endblock content %}

SSAFY/django/20230913/실습/pratice/articles/templates/articles/catchh.html
{% extends "base.html" %}

{% block content %}
<div class="container">
  <h1>Catchh</h1>
  <h1>{{name}}님 안녕하세요. </h1>
  <a href="{% url "articles:index" %}">index로 이동</a><br>
  <a href="{% url "articles:throw" %}">Throw로 이동</a>
 
</div>

{% endblock content %}

SSAFY/django/20230913/실습/pratice/articles/templates/articles/index.html
{% extends "base.html" %}

{% block content %}
<div class="container">
  <h1>
    index
  </h1>
  <h1>
    안녕하세요
  </h1>
  <a href="{% url "articles:throw" %}"> Throw로 이동</a>
</div>

{% endblock content %}

SSAFY/django/20230913/실습/pratice/articles/templates/articles/throw.html
{% extends "base.html" %}

{% block content %}
<div class="container">
  <h1>Throw</h1>
  <form action="{% url "articles:catch" %}">
    <input type="text" name="message">
    <input type="submit">
  </form>
  <a href="{% url "articles:index" %}">index로 이동</a>
</div>


{% endblock content %}